export { default as Account } from './Account';
export { default as Dashboard } from './Dashboard';
export { default as Icons } from './Icons';
export { default as NotFound } from './NotFound';
export { default as ProductList } from './ProductList';
export { default as Settings } from './Settings';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as Typography } from './Typography';
export { default as UserList } from './UserList';
export { default as UserForm } from './UserForm';
export { default as ProductForm } from './ProductForm';
export { default as PetList } from './PatientList';
export { default as PetForm } from './PatientForm';
export { default as Parameters } from './Parameters';
export { default as MedicalRecords } from './MedicalRecords';
export { default as Agenda } from './Agenda';
export { default as DoctorList } from './DoctorList'
export { default as DoctorForm } from './DoctorForm'
export { default as PatientList } from './PatientList'
export { default as PatientForm } from './PatientForm'
export { default as RecoverPassword } from './RecoverPassword'
